# Generated by Django 2.1.4 on 2018-12-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('main_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('E', 'Earning'), ('D', 'Deduction')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Job'),
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('employee.salaryothers',),
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('employee.salaryothers',),
        ),
    ]
